version: '3.5'

services:
  front:
    image: frontend
    build:
      context: ./
      dockerfile: front.Dockerfile
    ports:
      - 5000:5000
    container_name: ex02_front

  back:
    image: backend
    build:
      context: ./
      dockerfile: back.Dockerfile
    ports:
      - 8000:8000
    container_name: ex02_back
