version: '3.5'

services:
  frontend:
    image: frontend
    build:
      context: ./ml-kurkkumopo-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: machine_front

  backend:
    image: backend
    build:
      context: ./ml-kurkkumopo-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - training
    volumes:
      - ./model:/src/model
    container_name: machine_back

  training:
    image: training
    build:
      context: ./ml-kurkkumopo-training
      dockerfile: Dockerfile
    volumes:
      - ./model:/src/model
      - ./imgs:/src/imgs
    container_name: machine_training
