version: '3.5'

services:
  front:
    image: frontend
    build:
      context: ./
      dockerfile: front.Dockerfile
    ports:
      - 5000:5000
    container_name: ex05_front

  back:
    image: backend
    build:
      context: ./
      dockerfile: back.Dockerfile
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
    depends_on:
      - db
    container_name: ex05_back

  redis:
    image: redis
    container_name: ex05_redis

    db: 
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: ex05_db

