FROM node as build-stage

WORKDIR /app

RUN git clone https://github.com/stutommi/kaste_2.0-frontend.git . && \
    npm install && npm run build

FROM nginx

COPY --from=build-stage /app/build /usr/share/nginx/html

# Resulting image size: 130MB
